name: New Relic Change Tracking

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  newrelic:
    runs-on: ubuntu-latest
    steps:
      - name: New Relic Change Event
        uses: newrelic/deployment-marker-action@d88a59ea8f713ad6935e60de27273157790b1e3b # v2.6.2
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          guid: ${{ secrets.NEW_RELIC_DEPLOYMENT_ENTITY_GUID }}
          commandType: "changeTrackingCreateEvent"
          entitySearch: "id='${{ secrets.NEW_RELIC_DEPLOYMENT_ENTITY_GUID }}'"
          version: "${{ github.sha }}"
          category: "Deployment"
          type: "Basic"
          user: "${{ github.actor }}"
          description: "${{ github.event.head_commit.message }}"
