name: New Relic Change Tracking

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  newrelic:
    runs-on: ubuntu-latest
    steps:
      - name: Get Unix Timestamp
        id: timestamp
        run: echo "value=$(date +%s)" >> $GITHUB_OUTPUT

      - name: New Relic Change Event
        uses: newrelic/deployment-marker-action@85b4f6e10e8a134ae2fa62822768b8fcd4152fcd # v2.6.0
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          guid: ${{ secrets.NEW_RELIC_DEPLOYMENT_ENTITY_GUID }}
          commandType: "changeTrackingCreateEvent"
          entitySearch: "id='${{ secrets.NEW_RELIC_DEPLOYMENT_ENTITY_GUID }}'"
          version: "${{ github.sha }}"
          category: "Deployment"
          type: "Basic"
          user: "${{ github.actor }}"
          description: "${{ github.event.head_commit.message }}"
          timestamp: "${{ steps.timestamp.outputs.value }}"
